In [1]:
import pandas as pd

df = pd.read_csv("../data/passenger_master_with_pfi.csv")

df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Delay_Score,Service_Quality_Score,Service_Dissatisfaction,Travel_Difficulty,PFI,PFI_Category
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,25,18.0,neutral or dissatisfied,1.136364,3.857143,22.857143,8.663166,11.330036,Low Friction
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,6.0,neutral or dissatisfied,0.378788,2.285714,54.285714,4.119548,22.689710,Low Friction
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,0,0.0,satisfied,0.000000,3.714286,25.714286,22.435380,14.772790,Low Friction
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,11,9.0,neutral or dissatisfied,0.568182,3.000000,40.000000,10.722940,18.371861,Low Friction
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,0,0.0,satisfied,0.000000,3.500000,30.000000,3.695477,12.739095,Low Friction

In [2]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'sklearn'

In [2]:
persona_features = [
    "Flight Distance",
    "Service_Quality_Score",
    "PFI"
]

In [3]:
persona_features = [
    "Flight Distance",
    "Service_Quality_Score",
    "PFI"
]

In [4]:
X = df[persona_features]

X.head()

   Flight Distance  Service_Quality_Score        PFI
0              460               3.857143  11.330036
1              235               2.285714  22.689710
2             1142               3.714286  14.772790
3              562               3.000000  18.371861
4              214               3.500000  12.739095

In [6]:
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: No module named 'sklearn'